### ISSUE TITLE
ImportError Running Netaudio

### ISSUE THREAD

**Issue by klangfarben1** [chris-ritsen/network-audio-controller#12]
Hi, I've installed Netaudio on Manjaro/Arch and when I run any of the commands such as Netaudio Device List I get the following...

netaudio device list
Traceback (most recent call last):
  File "/usr/bin/netaudio", line 33, in <module>
    sys.exit(load_entry_point('netaudio==0.0.10', 'console_scripts', 'netaudio')())
  File "/usr/bin/netaudio", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/netaudio/__init__.py", line 10, in <module>
    from .console.application import main
  File "/usr/lib/python3.10/site-packages/netaudio/console/__init__.py", line 1, in <module>
    from .commands.channel import ChannelCommand
  File "/usr/lib/python3.10/site-packages/netaudio/console/commands/__init__.py", line 1, in <module>
    from .channel import ChannelCommand
  File "/usr/lib/python3.10/site-packages/netaudio/console/commands/channel/__init__.py", line 1, in <module>
    from cleo import Command
ImportError: cannot import name 'Command' from 'cleo' (/usr/lib/python3.10/site-packages/cleo/__init__.py)

**Comment by AWHubGit** [comment]
Same here. Installed by AUR in Arch with "--syncdeps". Running command "netaudio help" results in:
ImportError: cannot import name 'Command' from 'cleo' (/usr/lib/python3.10/site-packages/cleo/__init__.py)

**Comment by bfranske** [comment]
I think the DanteCache feature was never fully implemented/working when committed. Check an older version like https://github.com/chris-ritsen/network-audio-controller/tree/81eae884464211cdfb0e9d9093cea0146a3cc4f7

You can see a note about caching being under development on this thread https://gearspace.com/board/music-computers/1221989-dante-routing-without-dante-controller-possible.html Caching would be useful as it would speed up changes and save a lot of lookups if you want to change a large number of patches in a batch set for instance.

**Comment by chris-ritsen** [comment]
CLI has changed enough that this is likely no longer an issue. I've started publishing new releases on AUR to replace this broken one.
