### ISSUE TITLE
"timed out getting mDNS service" error

### ISSUE THREAD

**Issue by avotins** [chris-ritsen/network-audio-controller#15]
When using basic tool commands (device/subscription list) mdns service seams to timeout. This test deployment has quite a lot of Dante devices present in the space (about 50-60). In the end some device list is reported, but it does not represent all devices present in network.

Example:

^C[<user>@<server> ~]$ netaudio device list --name=<device-name>
timed out getting mDNS service
timed out getting mDNS service
timed out getting mDNS service
timed out getting mDNS service
timed out getting mDNS service
timed out getting mDNS service
timed out getting mDNS service
timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 277, in get_controls
    response = await self.dante_command(*self.command_device_name())
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 96, in dante_command
    response = sock.recvfrom(2048)[0]
socket.timeout: timed out
timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 277, in get_controls
    response = await self.dante_command(*self.command_device_name())
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 96, in dante_command
    response = sock.recvfrom(2048)[0]
socket.timeout: timed out
timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 277, in get_controls
    response = await self.dante_command(*self.command_device_name())
  File "/usr/local/lib/python3.9/site-packages/netaudio/dante/device.py", line 96, in dante_command
    response = sock.recvfrom(2048)[0]
socket.timeout: timed out

**Comment by chris-ritsen** [comment]
The timeout isn't configurable currently, but I'll look into making some options for it. I have far less than 50 devices, so the 1.5 second timeout I hardcoded worked for me. What kind of solution would be ideal? I've started implementing a daemon mode to cache to redis, but it's only on the list command right now. If you need to avoid the mDNS timeout, a workaround would be to specify devices by IP when doing anything besides listing devices.

**Comment by avotins** [comment]
Yes, I understand that I might be one of very few people working with that many dante devices usually it's up to 10-20 maybe. :) In general I wanted to basically have that be fully integrated so it is usable for scripting/automating & etc so that is with mdns, since when querying for network status it uses mdns, so some kind of dynamic mdns might work. On per device bases given specifics of dante you won't always know the exact IP of dante device, especially during setup where for large deployments this is very useful, subnet and even device name yes, but not the address as it is handled by mdns in most cases for normal users. I myself use static, but I'm not the only one that might find this useful. I will check if the workaround with IP works for me, but in any case just bringing it up as it might be useful for others also. I'm an edge case I know and thanks for the grate work! :)
