### ISSUE TITLE
SIGPIPE problem on Windows 10

### ISSUE THREAD

**Issue by alexsconway** [chris-ritsen/network-audio-controller#9]
Netaudio was installed using pip

Microsoft Windows [Version 10.0.19044.1766]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Alex>netaudio
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\Scripts\netaudio.exe\__main__.py", line 4, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\netaudio\__init__.py", line 10, in <module>
    from .console.application import main
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\netaudio\console\application.py", line 1, in <module>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name 'SIGPIPE' from 'signal' (C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\signal.py)

C:\Users\Alex>

**Comment by mixmog** [comment]
Also seeing this error

**Comment by AleksB27** [comment]
SIGPIPE is supported only in Unix, not WinXX

**Comment by alexsconway** [comment]
After removing the lines involving signal & SPIGPIE etc, it seems to work - at least for finding devices.
Could you put a try-except-pass around the signal stuff?
What does it do anyway?

**Comment by AleksB27** [comment]
I added this:
`try:
    from signal import signal, SIGPIPE, SIG_DFL
    signal(SIGPIPE, SIG_DFL)
except ImportError:  # If SIGPIPE is not available (win32),
    pass
`

but now getting another error - cannot import name 'Command' from 'cleo'
trying to solve it

**Comment by alexsconway** [comment]
@AleksB27 re: "but now getting another error - cannot import name 'Command' from 'cleo'"
that is a diffferent issue, please open another issue for it.
